### ISSUE TITLE
[enhancement] Diff buffers that not saved in files

### ISSUE THREAD

**Issue by kotomaran** [soandrew/DiffTabs#1]
How about to adding a feature when we can diff tabs that contain some text but not represent any files? Now it seems for me like this addon not working until I save involved buffers in files. When I try to do so console says:
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 795, in run_
    return self.run(**args)
  File "diff in /opt/sublime_text/Packages/Diff.sublime-package", line 13, in run
  File "./python3.3/codecs.py", line 896, in open
TypeError: invalid file: None
```

**Comment by soandrew** [comment]
Hmmm this is a use case that I never considered. Just to clarify, you would like it to be possible to compare two tabs without saving them first?

**Comment by kotomaran** [comment]
Yes, exactly. Compare just buffers of text (or "views" in terms of ST) without saving them on disk.

**Comment by soandrew** [comment]
With 80b6cdc, comparing buffers should now be the default behaviour. I agree that tabs with unsaved changes shouldn't need saving in order to compare them.
