### ISSUE TITLE
Is there a way to enable Ctl-Click on macOS? [SOLVED]

### ISSUE THREAD

**Issue by richb-hanover** [soandrew/DiffTabs#6]
Using macOS Catalina 10.15.4 on a MacBook Pro with ST 3.2.2 and DiffTabs 2.0.1 

DiffTabs works great when I have a mouse with a right-click button to diff two tabs.

Is there a way to simulate a right-click with a Control-click (or other keyboard combination)? This would be useful if I don't have an external mouse handy... Thanks.

**Comment by soandrew** [comment]
Hey, unfortunately I am not a Mac user so do not have a way to verify this, but as far as I am aware Control-click on a Mac is by default identical to a right click. If Control-click works in say Finder or Safari then it should work in Sublime.

I'm just basing this off of [this article](https://support.apple.com/en-ca/HT207700) and the few times in the past I've used a Mac, so let me know if your experience differs.

**Comment by richb-hanover** [comment]
I got a hint to a better solution on the Sublime Text forum. You can turn on two-finger tap on the trackpad to get a "secondary click". Works a treat.

[Here's the answer I posted to the Sublime Text forum.](https://forum.sublimetext.com/t/control-click-for-macos/51269/3)

PS Thanks for DiffTabs - I think I'll use it a lot.

**Comment by soandrew** [comment]
Glad you found a solution that works for you!
