### ISSUE TITLE
Doesn't seem to work with Sublime 4126

### ISSUE THREAD

**Issue by 0xdevalias** [soandrew/DiffTabs#7]
Just tried installing this in Sublime 4126 via Package Control, but i'm not seeing the context menu/similar appear anywhere.

**Comment by soandrew** [comment]
Hi, sorry for the late response, was just able to test with Sublime 4126 and the plugin appears to be working as expected.

You need two tabs open in the editor first, and the context menu option should appear for the tab you don't currently have focus on

**Comment by 0xdevalias** [comment]
Thanks for checking this out + the extra pointers on usage. I've just confirmed that it definitely does work on Sublime 4126 for me as well.. I must have just not realised how to use it properly the other day or similar.

The usage gif you added to the README in https://github.com/soandrew/DiffTabs/commit/b05f11e646c8d2d62f20743c65ccbd498db0ce29 is super helpful. Thanks :)
